# Generated by Django 5.2.3 on 2025-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='car_pictures/default.png', null=True, upload_to='media/car_pictures/'),
        ),
    ]
