# Generated by Django 5.2.3 on 2025-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='car_pictures/default.png', upload_to='media/car_pictures/'),
        ),
    ]
