# Generated by Django 5.2.3 on 2025-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
    ]
