# Generated by Django 5.2.3 on 2025-08-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
